nodenext compatibility
fastify/fastify-compress pull request #247
Opened 2022-11-23 09:19 UTC by Uzlopak

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2022-11-23 10:08 UTC, climba03003 requested changes

2022-11-23 10:40 UTC, Uzlopak commented on index.d.ts
> +  export interface RouteOptions extends FastifyRouteOptions, FastifyCompressRouteOptions { }
will have a look

2022-11-23 13:13 UTC, Uzlopak commented
@climba03003 PTAL

2022-11-24 14:14 UTC, climba03003 approved these changes

2022-11-24 14:19 UTC, merged