perf(index): use sensible brotli value as default
fastify/fastify-compress pull request #278
Opened 2024-01-28 13:21 UTC by kahlstrm

The default brotli quality value currently is 11, which is not meant to be used in an on the fly compression context. Change this to a more reasonable default value of 4.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-01-28 13:29 UTC, Uzlopak commented on index.js
> +    brotliOptions: { [zlib.constants.BROTLI_PARAM_QUALITY]: 4, ...opts.brotliOptions },
```suggestion
    brotliOptions: { [zlib.constants.BROTLI_PARAM_QUALITY]: 4, ...opts.brotliOptions }
```

2024-01-28 13:30 UTC, gurgunday commented
This looks like a pretty good change

Choosing anything higher than 6 has significant impact on the performance for little benefit 

Ref: https://github.com/dotnet/runtime/issues/26097#issuecomment-388434527

2024-01-28 13:35 UTC, kahlstrm commented
> This looks like a pretty good change
> 
> Choosing anything higher than 6 has significant impact on the performance for little benefit
> 
> Ref: [dotnet/runtime#26097 (comment)](https://github.com/dotnet/runtime/issues/26097#issuecomment-388434527)

In this case 4 was chosen as it's apparently a default used by Cloudflare. [Related](https://blog.cloudflare.com/results-experimenting-brotli). Here level 5 provides some advantages at files above 64KB so that would also be an alternative.

2024-01-28 13:42 UTC, Uzlopak commented
Yeah, makes sense. I also was avoiding brotli for the same reason, and preferred gzip as it has higher throughput. But maybe with brotli compression factor of 4 this drawback does not exist anymore.

2024-01-28 13:45 UTC, Uzlopak commented
what does the title mean? sensible brotli value? Maybe some more distinctive title is good, so that reading the release notes it can be determined what changed.

`perf: reduce default brotli compression factor to 4, was before 11 (maximum)`

2024-01-28 13:50 UTC, gurgunday approved these changes
Will lgtm after the title change :)

2024-01-28 14:26 UTC, Uzlopak approved these changes
LGTM

2024-01-28 20:01 UTC, Fdawgs requested changes
Maybe put an inline comment referencing why we've set the default to 4?

2024-01-29 09:09 UTC, Fdawgs approved these changes

2024-01-29 09:15 UTC, SimenB commented
I'd argue changing the default is a breaking change, and not a "performance improvement". I agree it's a better default, but the behaviour shouldn't change without the consumer having the chance to decide if they value throughput over compression

2024-01-29 09:23 UTC, climba03003 commented
> I'd argue changing the default is a breaking change

Yes, it is.

> the behaviour shouldn't change without the consumer having the chance to decide if they value throughput over compression

@SimenB Maybe you overlook the code, it still allow to change the value in `brotliOptions`. The predefined one is before the spread operator which means it is non-configurable.

2024-01-29 09:47 UTC, Uzlopak commented
As it is breaking the api contract i also concur , that it is a semver-major.

2024-01-29 09:47 UTC, mcollina commented
> I'd argue changing the default is a breaking change, and not a "performance improvement".

I'm ok in bumping a major for this.

---

>  I agree it's a better default, but the behaviour shouldn't change without the consumer having the chance to decide if they value throughput over compression

Is this implemented already? https://github.com/fastify/fastify-compress?tab=readme-ov-file#brotlioptions-and-zliboptions

2024-01-29 13:39 UTC, Uzlopak commented
@mcollina 

Yes:
https://github.com/fastify/fastify-compress/blob/9e45ec99935d67e17a05ecfd386bd405f6bdb87f/index.js#L135

2024-01-29 13:53 UTC, SimenB commented
Yes, the user can set it (IIRC we did lower it at my previous workplace) - I'm just pointing out changing the default (even if configurable) is breaking 🙂 When I said "user should have the chance to decide" I merely meant a major version will "force" the user to make a conscious choice, rather than a `perf` version, which is usually a patch release which I assume most people don't comb through changelogs for

2024-01-29 13:59 UTC, Uzlopak commented
@SimenB 
And to what value did you reduce it?

2024-01-29 14:56 UTC, gurgunday commented
8 seems too much 😅, but I fully get that it is much better than the current default

64kb is significant for text data, I don't believe the average size of an HTML page or a CSS file is up there

I think 4 is a good default

2024-01-29 15:02 UTC, kahlstrm commented
> 8 seems too much 😅, but I fully get that it is much better than the current default
> 
> 64kb is significant for text data, I don't believe the average size of an HTML page or a CSS file is up there
> 
> I think 4 is a good default

Note that in the snippet zlib is set at 8, which is comparable to brotli quality 4 IIRC. The brotli level inthe snippet is below to level 5.

2024-01-29 17:59 UTC, merged