Polish test case for PR: replace `into-stream` to `Readable.from`
fastify/fastify-compress pull request #291
Opened 2024-03-30 12:12 UTC by stanleyxu2005

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-03-30 12:14 UTC, stanleyxu2005 commented
I'd like to polish the test case @climba03003 and @mcollina create. But it's strage that your previous PR and this PR are failing at my local env.

2024-03-30 12:54 UTC, stanleyxu2005 commented
If I replace `unidici` with `axois`, it works
```js
  // const response1 = await request(`${address}/compress`)
  // const response2 = await request(`${address}/no-compress`)
  // const body1 = await response1.body.text()
  // const body2 = await response2.body.text()
  const body1 = (await axios(`${address}/compress`)).data
  const body2 = (await axios(`${address}/no-compress`)).data
  t.equal(body1, body2)
  t.equal(body1.length, twoByteUnicodeContent.length)
  t.equal(body2.length, twoByteUnicodeContent.length)
```

2024-03-30 13:19 UTC, gurgunday commented
That's interesting

node 14 doesn't support undici fetch I think... you might want to try `node-fetch@2` if you'd like to use it here

2024-03-30 13:33 UTC, climba03003 commented
I don't understand why it is strange on your environment. The test case works fine between different OS and Node versions. 

I have also tested on my local environment.
What's the problem of `undici.request` ?

2024-03-30 13:46 UTC, stanleyxu2005 commented
> I don't understand why it is strange on your environment. The test case works fine between different OS and Node versions.
> 
> I have also tested on my local environment. What's the problem of `undici.request` ?

Before I removed `unidici`, received response text lengths are not identical. You can check the attached screenshot and also the first couple of pipeline failure reports.

2024-03-30 14:05 UTC, gurgunday commented
> I don't understand why it is strange on your environment. The test case works fine between different OS and Node versions.
> 
> I have also tested on my local environment. What's the problem of `undici.request` ?

@climba03003 I was going to ask if you had an idea on why `undici.request` might be returning a different response text length, maybe there is some post processing based on the charset of the response?

So request didn't work: https://github.com/fastify/fastify-compress/pull/291/commits/ffe60f61defc6a70e5015e9b9ecfa355d606b6b4

And fetch did: https://github.com/fastify/fastify-compress/pull/291/commits/c1882b91b6044f45c197cf8562ece0133ea5919d

2024-03-30 14:09 UTC, gurgunday commented on package.json
> +    "node-fetch": "2",
```suggestion
    "node-fetch": "^2",
```

2024-03-30 14:11 UTC, stanleyxu2005 commented
> I don't understand why it is strange on your environment. The test case works fine between different OS and Node versions.
> 
> I have also tested on my local environment. What's the problem of `undici.request` ?

Here are my thoughts of failing or not failing @climba03003 

(1) In my attached img, the input length (334k) and output length (284k) are not identical.

(1) The previous PR you created, only checks the responses of compressed and uncompressed. They are identical on supported platforms (including my dev env1 - Win11), but for some reasons, not identical on my dev env2 - a legacy Windows.

(2) In my PR, I check the input and output length in additional. That's why it is failed. 

(3) Why the input and output lengths are not same, maybe there are some hidden settings for encoding. I'm not familiar with `unidici`, so I cannot tell, if it is a bug of `unidici` or not.

![image](https://github.com/fastify/fastify-compress/assets/5162687/92eefb8e-6656-4e4c-b0ee-0f2ffe93abbf)

2024-03-30 14:22 UTC, gurgunday approved these changes
lgtm

2024-03-30 16:30 UTC, mcollina requested changes
Please use use my test. undici.fetch() correctly decode this. undici.request() for some reason does not. I'll open an issue.

Use undici@5.

2024-03-30 17:50 UTC, gurgunday commented
@mcollina undici fetch doesn’t work in node 14 I think, do you know if that’s the case?

2024-03-31 07:41 UTC, mcollina approved these changes
lgtm

2024-03-31 07:42 UTC, mcollina commented
You are right, there is no web streams in node v14.

2024-03-31 07:42 UTC, merged